---
format:
  pdf:
    tbl-cap-location: top
    dpi: 500
    fig-pos: "H"
    number-sections: true
    cite-method: natbib
    include-in-header: 
      - text: |
          \usepackage{lscape}
          \newcommand{\blandscape}{\begin{landscape}}
          \newcommand{\elandscape}{\end{landscape}}
          \usepackage{rotating}
      - file: preamble.tex
    include-before-body: title.tex
  docx:
    reference-doc: new_template_no_numbering.docx
pdf-engine: xelatex
# monofont: "DejaVu Sans Mono"
# mainfont: "Times New Roman"
execute: 
  echo: false
  warning: false
editor: source
bibliography: references.bib
biblio-style: apalike
natbiboptions: round
link-citations: true
linkcolor: blue!000!black
urlcolor: blue!000!black
citecolor: blue!000!black
linestretch: 1.5
indent: TRUE
title-block-banner: false
title-block-style: none
---

```{r setup}
#| include=FALSE
options(scipen=999)
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      dpi = 500, 
                      fig.pos = "H", 
                      fig.env= 'figure', 
                      tab.topcaption = FALSE,
                      ft.align = "left"
                      
                      )
library(tidyverse)
library(readr)
library(readxl)
library(zoo)
library(magick)
library(stringi)
library(patchwork)
library(xtable)
library(scales)
library(rvest)
library(rebus)
library(PNWColors)
library(lubridate)
library(here)
library(flextable)
library(gt)
library(officer)
library(officedown)
library(modelsummary)
library(sandwich)
library(lmtest)
```

```{r functions}
source(here("Functions","flextable_word.R" ))
source(here("Functions","modelsummary_word.R" ))
source(here("Functions","modelplot_word.R" ))
source(here("Functions","borderlines.R" ))
```


# Introduction


# Literature Review
@alexakis2023animal

# Data and Methodology

# Results

# Conclusion

\newpage
# References 
::: {#refs}
:::


\setcounter{section}{0}
\renewcommand{\thesection}{\Alph{section}}

\setcounter{table}{0}
\renewcommand{\thetable}{A\arabic{table}}

\setcounter{figure}{0}
\renewcommand{\thefigure}{A\arabic{figure}}

\newpage

# Appendix

## Data










